from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from typing import Protocol

from adaptiveroute.domain.events import OperationalEvent
from adaptiveroute.domain.models import RoutingPlan, RoutingScenario
from adaptiveroute.domain.serialization import event_to_dict, scenario_to_dict, validation_to_dict
from adaptiveroute.llm.openai_compatible import OpenAICompatibleChatClient, OpenAICompatibleSettings
from adaptiveroute.services.counterfactual import build_plan_from_route_sequences
from adaptiveroute.services.validation import validate_plan
from adaptiveroute.solvers.base import RoutingEngine
from adaptiveroute.training.prompt_format import SYSTEM_PROMPT, build_user_prompt


@dataclass(frozen=True)
class CandidateGenerationResult:
    plan: RoutingPlan | None
    source: str
    message: str = ""


class RoutingCandidateGenerator(Protocol):
    def generate(
        self,
        scenario: RoutingScenario,
        event: OperationalEvent,
        base_plan: RoutingPlan,
    ) -> CandidateGenerationResult:
        """Generate a candidate route plan for the replanning scenario."""


class SolverBackedCandidateGenerator:
    """Deterministic candidate generator used until the LoRA serving path is wired.

    It implements the same interface expected from the fine-tuned routing policy.
    That keeps the LangGraph workflow testable without requiring a local model
    server or loading the 7B adapter during unit tests.
    """

    def __init__(self, engine: RoutingEngine, source: str = "solver_candidate"):
        self._engine = engine
        self._source = source

    def generate(
        self,
        scenario: RoutingScenario,
        event: OperationalEvent,
        base_plan: RoutingPlan,
    ) -> CandidateGenerationResult:
        result = self._engine.solve(scenario)
        if result.plan is None:
            return CandidateGenerationResult(plan=None, source=self._source, message=result.message)
        return CandidateGenerationResult(plan=result.plan, source=self._source, message="Generated by solver-backed candidate generator.")


def build_routing_candidate_generator_from_env(engine: RoutingEngine) -> RoutingCandidateGenerator:
    backend = os.getenv("ADAPTIVEROUTE_ROUTING_POLICY_BACKEND", "solver").strip().lower()
    if backend in {"solver", "deterministic", ""}:
        return SolverBackedCandidateGenerator(engine, source="solver_candidate")
    if backend == "api":
        return ApiRoutingCandidateGenerator.from_env()
    if backend in {"local", "direct"}:
        return LocalLoraRoutingCandidateGenerator.from_env()
    raise ValueError(
        "Unsupported ADAPTIVEROUTE_ROUTING_POLICY_BACKEND. "
        "Use one of: solver, api, local."
    )


class ApiRoutingCandidateGenerator:
    """Routing candidate generator backed by an OpenAI-compatible policy model."""

    def __init__(
        self,
        client: OpenAICompatibleChatClient,
        *,
        source: str | None = None,
        max_retries: int = 2,
    ):
        self._client = client
        self._source = source or f"api_candidate:{client.selected_model}"
        self._max_retries = max(0, max_retries)

    @classmethod
    def from_env(cls, prefix: str = "ADAPTIVEROUTE_ROUTING_POLICY") -> "ApiRoutingCandidateGenerator":
        return cls(
            OpenAICompatibleChatClient(OpenAICompatibleSettings.from_env(prefix=prefix)),
            max_retries=int(os.getenv(f"{prefix}_MAX_RETRIES", "2")),
        )

    def generate(
        self,
        scenario: RoutingScenario,
        event: OperationalEvent,
        base_plan: RoutingPlan,
    ) -> CandidateGenerationResult:
        reusable_base_plan = _reusable_base_plan(scenario, base_plan)
        if reusable_base_plan is not None:
            return CandidateGenerationResult(
                plan=reusable_base_plan,
                source=f"{self._source}:base_plan_reused",
                message="Existing route plan remains valid after the event; reused without LLM regeneration.",
            )

        row = _build_policy_row(scenario, event, base_plan)
        user_prompt = build_user_prompt(row)
        attempts: list[str] = []
        try:
            last_error = ""
            last_plan: RoutingPlan | None = None
            for attempt in range(1, self._max_retries + 2):
                response = self._client.chat(
                    system=_policy_system_prompt(attempt),
                    user=user_prompt,
                    temperature=0,
                    response_format={"type": "json_object"},
                )
                try:
                    plan = _build_plan_from_policy_text(scenario, response.content)
                    validation = validate_plan(scenario, plan)
                except Exception as exc:
                    last_error = str(exc)
                    attempts.append(f"attempt {attempt}: parse/build error: {last_error}")
                    if attempt > self._max_retries:
                        break
                    user_prompt = _build_correction_prompt(row, response.content, {"error": last_error})
                    continue

                last_plan = plan
                if validation.passed:
                    attempts.append(f"attempt {attempt}: valid")
                    return CandidateGenerationResult(
                        plan=plan,
                        source=self._source,
                        message=f"Generated by {response.model} after {attempt} attempt(s). {'; '.join(attempts)}",
                    )

                validation_payload = validation_to_dict(validation)
                last_error = json.dumps(validation_payload, ensure_ascii=False)
                attempts.append(f"attempt {attempt}: invalid: {_compact_validation_feedback(validation_payload)}")
                if attempt > self._max_retries:
                    break
                user_prompt = _build_correction_prompt(row, response.content, validation_payload)

            return CandidateGenerationResult(
                plan=last_plan,
                source=self._source,
                message=f"Routing policy failed after {self._max_retries + 1} attempt(s). {'; '.join(attempts)}. Last error: {last_error}",
            )
        except Exception as exc:
            return CandidateGenerationResult(plan=None, source=self._source, message=str(exc))


class LocalLoraRoutingCandidateGenerator:
    """Routing candidate generator that loads the trained LoRA adapter in-process."""

    def __init__(
        self,
        *,
        model_id: str = "Qwen/Qwen2.5-7B-Instruct",
        adapter_path: str | Path = "outputs/models/adaptiveroute-qwen2_5-7b-lora-error20k-v5",
        served_model_name: str = "adaptiveroute-routing-policy",
        max_new_tokens: int = 256,
        use_4bit: bool = True,
        bf16: bool = True,
        load_at_startup: bool = False,
        max_retries: int = 2,
    ):
        self._model_id = model_id
        self._adapter_path = Path(adapter_path)
        self._served_model_name = served_model_name
        self._max_new_tokens = max_new_tokens
        self._use_4bit = use_4bit
        self._bf16 = bf16
        self._max_retries = max(0, max_retries)
        self._source = f"local_lora_candidate:{served_model_name}"
        self._lock = Lock()
        self._loaded = False
        self._tokenizer = None
        self._model = None
        if load_at_startup:
            self.load()

    @classmethod
    def from_env(cls, prefix: str = "ADAPTIVEROUTE_ROUTING_POLICY") -> "LocalLoraRoutingCandidateGenerator":
        return cls(
            model_id=os.getenv(f"{prefix}_LOCAL_MODEL_ID", "Qwen/Qwen2.5-7B-Instruct"),
            adapter_path=os.getenv(
                f"{prefix}_LOCAL_ADAPTER_PATH",
                "outputs/models/adaptiveroute-qwen2_5-7b-lora-error20k-v5",
            ),
            served_model_name=os.getenv(f"{prefix}_MODEL", "adaptiveroute-routing-policy"),
            max_new_tokens=int(os.getenv(f"{prefix}_LOCAL_MAX_NEW_TOKENS", "256")),
            use_4bit=_env_bool(f"{prefix}_LOCAL_4BIT", True),
            bf16=_env_bool(f"{prefix}_LOCAL_BF16", True),
            load_at_startup=_env_bool(f"{prefix}_LOCAL_LOAD_AT_STARTUP", False),
            max_retries=int(os.getenv(f"{prefix}_MAX_RETRIES", "2")),
        )

    @property
    def loaded(self) -> bool:
        return self._loaded

    def load(self) -> None:
        with self._lock:
            if self._loaded:
                return

            import torch
            from peft import PeftModel
            from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

            tokenizer = AutoTokenizer.from_pretrained(self._adapter_path, trust_remote_code=True)
            if tokenizer.pad_token_id is None:
                tokenizer.pad_token = tokenizer.eos_token

            quantization_config = None
            if self._use_4bit:
                quantization_config = BitsAndBytesConfig(
                    load_in_4bit=True,
                    bnb_4bit_compute_dtype=torch.bfloat16 if self._bf16 else torch.float16,
                    bnb_4bit_quant_type="nf4",
                    bnb_4bit_use_double_quant=True,
                )

            base = AutoModelForCausalLM.from_pretrained(
                self._model_id,
                trust_remote_code=True,
                device_map="auto",
                torch_dtype=torch.bfloat16 if self._bf16 else "auto",
                quantization_config=quantization_config,
            )
            model = PeftModel.from_pretrained(base, self._adapter_path)
            model.eval()

            self._tokenizer = tokenizer
            self._model = model
            self._loaded = True

    def generate(
        self,
        scenario: RoutingScenario,
        event: OperationalEvent,
        base_plan: RoutingPlan,
    ) -> CandidateGenerationResult:
        reusable_base_plan = _reusable_base_plan(scenario, base_plan)
        if reusable_base_plan is not None:
            return CandidateGenerationResult(
                plan=reusable_base_plan,
                source=f"{self._source}:base_plan_reused",
                message="Existing route plan remains valid after the event; reused without LLM regeneration.",
            )

        row = _build_policy_row(scenario, event, base_plan)
        user_prompt = build_user_prompt(row)
        attempts: list[str] = []
        try:
            last_error = ""
            last_plan: RoutingPlan | None = None
            for attempt in range(1, self._max_retries + 2):
                content = self._generate_text(
                    [
                        {"role": "system", "content": _policy_system_prompt(attempt)},
                        {"role": "user", "content": user_prompt},
                    ]
                )
                try:
                    plan = _build_plan_from_policy_text(scenario, content)
                    validation = validate_plan(scenario, plan)
                except Exception as exc:
                    last_error = str(exc)
                    attempts.append(f"attempt {attempt}: parse/build error: {last_error}")
                    if attempt > self._max_retries:
                        break
                    user_prompt = _build_correction_prompt(row, content, {"error": last_error})
                    continue

                last_plan = plan
                if validation.passed:
                    attempts.append(f"attempt {attempt}: valid")
                    return CandidateGenerationResult(
                        plan=plan,
                        source=self._source,
                        message=f"Generated by local adapter {self._adapter_path} after {attempt} attempt(s). {'; '.join(attempts)}",
                    )

                validation_payload = validation_to_dict(validation)
                last_error = json.dumps(validation_payload, ensure_ascii=False)
                attempts.append(f"attempt {attempt}: invalid: {_compact_validation_feedback(validation_payload)}")
                if attempt > self._max_retries:
                    break
                user_prompt = _build_correction_prompt(row, content, validation_payload)

            return CandidateGenerationResult(
                plan=last_plan,
                source=self._source,
                message=f"Local routing policy failed after {self._max_retries + 1} attempt(s). {'; '.join(attempts)}. Last error: {last_error}",
            )
        except Exception as exc:
            return CandidateGenerationResult(plan=None, source=self._source, message=str(exc))

    def _generate_text(self, messages: list[dict[str, str]]) -> str:
        self.load()
        tokenizer = self._tokenizer
        model = self._model
        if tokenizer is None or model is None:
            raise RuntimeError("Local LoRA policy model failed to load.")

        import torch

        prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        with self._lock:
            with torch.no_grad():
                generated = model.generate(
                    **inputs,
                    max_new_tokens=self._max_new_tokens,
                    do_sample=False,
                    pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
                )
        prompt_len = inputs["input_ids"].shape[-1]
        return tokenizer.decode(generated[0][prompt_len:], skip_special_tokens=True).strip()


def _build_policy_row(
    scenario: RoutingScenario,
    event: OperationalEvent,
    base_plan: RoutingPlan,
) -> dict:
    scenario_payload = scenario_to_dict(scenario)
    return {
        "input": {
            "depot": scenario_payload["depot"],
            "vehicles": scenario_payload["vehicles"],
            "customers": scenario_payload["customers"],
            "base_routes": {route.vehicle_id: list(route.stops) for route in base_plan.routes},
            "event": event_to_dict(event),
        }
    }


def _build_plan_from_policy_text(scenario: RoutingScenario, text: str) -> RoutingPlan:
    payload = _extract_json_object(text)
    route_sequences = _extract_route_sequences(payload)
    return build_plan_from_route_sequences(scenario, route_sequences)


def _reusable_base_plan(scenario: RoutingScenario, base_plan: RoutingPlan) -> RoutingPlan | None:
    candidate = RoutingPlan(
        scenario_id=scenario.id,
        routes=base_plan.routes,
        total_distance=base_plan.total_distance,
    )
    validation = validate_plan(scenario, candidate)
    return candidate if validation.passed else None


def _policy_system_prompt(attempt: int) -> str:
    if attempt <= 1:
        return SYSTEM_PROMPT
    return (
        f"{SYSTEM_PROMPT}\n\n"
        "Correction mode is active. You previously returned an invalid route plan. "
        "Use the validation feedback in the user message as hard constraints. "
        "Return only one JSON object with the exact schema {\"routes\":{\"vehicle_id\":[\"D0\",\"C1\",\"D0\"]}}. "
        "Every route must start and end at the depot. Use only known vehicle ids and active customer ids. "
        "Every active required customer must appear exactly once unless the scenario marks it inactive. "
        "Do not use blocked arcs. Respect vehicle capacity. Do not explain the answer outside JSON."
    )


def _build_correction_prompt(row: dict, previous_response: str, feedback: dict) -> str:
    return (
        "Regenerate the route plan as corrected JSON.\n\n"
        "Original routing input JSON:\n"
        f"{json.dumps(row['input'], ensure_ascii=False, sort_keys=True)}\n\n"
        "Previous invalid model response:\n"
        f"{previous_response}\n\n"
        "Validation feedback JSON. Fix every listed issue:\n"
        f"{json.dumps(feedback, ensure_ascii=False, sort_keys=True)}\n\n"
        "Return only valid JSON in this schema:\n"
        "{\"routes\":{\"<vehicle_id>\":[\"<depot_id>\",\"<customer_id>\",\"<depot_id>\"]}}"
    )


def _compact_validation_feedback(validation_payload: dict) -> str:
    violations = validation_payload.get("violations") if isinstance(validation_payload, dict) else None
    if not isinstance(violations, list):
        return str(validation_payload)[:500]
    return "; ".join(
        f"{violation.get('code')}: {violation.get('message')}"
        for violation in violations[:8]
        if isinstance(violation, dict)
    )


def _extract_json_object(text: str) -> dict:
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = stripped.strip("`").strip()
        if stripped.lower().startswith("json"):
            stripped = stripped[4:].strip()

    try:
        decoded = json.loads(stripped)
    except json.JSONDecodeError:
        start = stripped.find("{")
        end = stripped.rfind("}")
        if start < 0 or end < start:
            raise ValueError("Routing policy response did not contain a JSON object.")
        decoded = json.loads(stripped[start : end + 1])

    if not isinstance(decoded, dict):
        raise ValueError("Routing policy response JSON must be an object.")
    return decoded


def _extract_route_sequences(payload: dict) -> dict[str, list[str]]:
    if isinstance(payload.get("plan"), dict):
        payload = payload["plan"]

    routes = payload.get("routes")
    if not isinstance(routes, dict):
        raise ValueError("Routing policy response must include a top-level routes object.")

    parsed: dict[str, list[str]] = {}
    for vehicle_id, stops in routes.items():
        if not isinstance(vehicle_id, str):
            raise ValueError("Route vehicle ids must be strings.")
        if not isinstance(stops, list) or not all(isinstance(stop, str) for stop in stops):
            raise ValueError(f"Route stops for {vehicle_id} must be a list of strings.")
        parsed[vehicle_id] = stops

    return parsed


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None or raw == "":
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}
